name: CI
on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  lint:
    name: Lint custom-collector
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup go 1.14
        uses: actions/setup-go@v2
        with: {go-version: '1.14'}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          args: --verbose --config test/.golangci.yml --enable gofmt --enable goimports
        if: matrix.os != 'windows-latest'
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          args: --verbose --config test/.golangci.yml
        if: matrix.os == 'windows-latest'

  zip-collector:
    name: zip-collector
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup go 1.14
        uses: actions/setup-go@v2
        with: {go-version: '1.14'}
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build zip-collector
        run: go build .
        working-directory: zip-collector
      - name: Build autoruns-collector
        run: |
          go generate
          go build .
        working-directory: autoruns-collector

      - name: Run zip-collector
        run: |
          ./zip-collector.exe
          cat *.log
        if: matrix.os == 'windows-latest'
        shell: bash
        working-directory: zip-collector

      - name: Move Binary
        run: |
          mkdir bin store
          mv zip-collector/zip-collector* bin
        shell: bash

      - name: Upload zip-collector
        uses: actions/upload-artifact@master
        with:
          name: zip-collector ${{ matrix.os }}
          path: bin